# code for the motivating example in introduction section
# read in the intermediate data generated by 'motivatingExample.R' and output a .csv file
sds = c(1, 1.414214)
ps = c(100, 200, 500, 1000)
i = 0
results = matrix(ncol=16, nrow=length(sds)*length(ps))
# read and extract the result
for (sd in sds) {
  for (p in ps) {
    load(paste0("results/motivatingExample_sd=", sd, "_p=", p, ".Rdata"))
    i <- i + 1
    results[i, ] <- c(sd, p, colMeans(result))
  }
}
strs = c("mean", "lasso", "scad", "svm", "rf", "xgb",  "nn")
col_names  = c("sd", "p", as.vector(rbind(paste0(strs, "_tr"), paste0(strs, "_est"))))
results_df = data.frame(results)
colnames(results_df) = col_names
# output the result to .csv file
write.csv(results_df, "motivatingExample.csv")
